travis:
  secure:
    BINSTAR_TOKEN: dKQU/eax0GrgZiAncAAuvNv8aoDkMb792dMGRWUVUK/Wz355Tf0wXfm5JEWaeST1WeBfE2BH2BDNQNpETn7cz9gIt3Uzpxqfvb03AL097fef4UoLplH1h5vFrvr9rR6TIk8NI7C0s+ZKI6kDAu7O6dvCuNHiRILcsD2+x696t8LcCyQDmDHbQxOh/nKEMeXXb0GBO30iKRimDPqJIZMRWY2b//m8/0AGs34XlMbGBYouaGLBlycIn5tLwXQx+rdRx5loVwAMeR828drQwSFmsx+Tqoyrez5W3OY/HtNS6yGZgN4imbknLW/fBeP5LnPaNCneXUkmu2z2OEpXLO9jKN0dhbNjFmwfBXtSaG4yfjwdI05/iKDzaHSRc6OTMw5zNERTJTTJ5JqqS5ooqzJe7C0KGyf/6Xg0eZk8bv3PAXeTlDDuSCI1rrrq/XAJ3Umchvu3WfunK1LuRmpAOUJPS3r7ie/KzRFhyLEL4oeKSYD/C9qAZEfQMj25CHr/RbHBrOelzSsW7vWSLGi4K82LM4FQnlSE5zKNErdRy8I26cbd9kv5JSnGV1w/3Q7vwjMLC5i5c+xPlWgpxDikKe48or4wctywW6lKccgkxg0WawdRVPqEIsaZBQhdNllSQXLK9HaC+j3ZT9JB/D0U1L8H3pL3JHhCtrrn4QNtCjZTAFE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
