travis:
  secure:
    BINSTAR_TOKEN: fb5ugQOqE04byf52LpI+8zdmmiJjw2Tk9bniat3BuNR7lP/xoZGq89YijdmpApG4Mq2hoijgogWPAnhYOl7Xs0DycOOOKNPweDubVeGTxZXCGh6qPgptzy2mmo2vD2GUfvL5A4G+dAelUI9itQrEew9cimCKv0VMvqg/8eSEfQk04aWeu4IpW1AaSolEiPt1bu9UotUBoC195Nv61HU7F9BENjS9kFZ68b7LZsAOOvnKLjiMDZe6ElVamYLYtNyG/S2UvQjz5+//AinJXvmv1Uo2uEDPTeu+RjUsvyzX5f7HbrUMw5R/RWFjH66wBdQkTRkXUEIh3E9OFTWVWBFl5ZGSn/lF8HzugVxowneekAWqmFeSacCYQEXbeRxqFHrp/Xl1yo4RE2CzSfLao4WTreLyW00sMBj/G8hm5de1fk0PAp5BlcgwbET2234U1q0rQSGi3S5AB6eydXhhXtdkcmhTEL9/HXGutlRmrDrgEu5Umk2gLPbELKiXj/YcNHfb9Q21YnI/n7gHrnpFtFdcjfjMLwug2SYzxKy0/bsfca80b6aOikmH33qdJ15ULHTMNotlZWEu/FEu841FQaKCRzKP/LW2Mp1yJZvG1WwddKCNz2cy9I7nb+Yp5Pq9AwyBfU8OYG4+0AKGTOU/zJQSmHDLrfnePB7fqYVm0FDMtf8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
